// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2FRhCcAGyhsx3SHcp1Jvnj4-rHhf_Q8',
    appId: '1:695231421681:web:d768dc43b759994b381d50',
    messagingSenderId: '695231421681',
    projectId: 'lingualearn-2e81e',
    authDomain: 'lingualearn-2e81e.firebaseapp.com',
    databaseURL: 'https://lingualearn-2e81e-default-rtdb.firebaseio.com',
    storageBucket: 'lingualearn-2e81e.firebasestorage.app',
    measurementId: 'G-88BELX7WVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAUlOHuDfdJu7ep0Sa3aVdrskysXh-07s',
    appId: '1:695231421681:android:5fe40ef19a4f0c3a381d50',
    messagingSenderId: '695231421681',
    projectId: 'lingualearn-2e81e',
    databaseURL: 'https://lingualearn-2e81e-default-rtdb.firebaseio.com',
    storageBucket: 'lingualearn-2e81e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KHjadRxwmIyMa2YcFxyBwTtAqsd2txE',
    appId: '1:695231421681:ios:3b1540b9d6285b4d381d50',
    messagingSenderId: '695231421681',
    projectId: 'lingualearn-2e81e',
    databaseURL: 'https://lingualearn-2e81e-default-rtdb.firebaseio.com',
    storageBucket: 'lingualearn-2e81e.firebasestorage.app',
    iosBundleId: 'com.example.lingualearn',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8KHjadRxwmIyMa2YcFxyBwTtAqsd2txE',
    appId: '1:695231421681:ios:3b1540b9d6285b4d381d50',
    messagingSenderId: '695231421681',
    projectId: 'lingualearn-2e81e',
    databaseURL: 'https://lingualearn-2e81e-default-rtdb.firebaseio.com',
    storageBucket: 'lingualearn-2e81e.firebasestorage.app',
    iosBundleId: 'com.example.lingualearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2FRhCcAGyhsx3SHcp1Jvnj4-rHhf_Q8',
    appId: '1:695231421681:web:8d64c30829efd817381d50',
    messagingSenderId: '695231421681',
    projectId: 'lingualearn-2e81e',
    authDomain: 'lingualearn-2e81e.firebaseapp.com',
    databaseURL: 'https://lingualearn-2e81e-default-rtdb.firebaseio.com',
    storageBucket: 'lingualearn-2e81e.firebasestorage.app',
    measurementId: 'G-Z7YQW0ZL0J',
  );
}
